source 'https://rubygems.org'
source 'https://gem.fury.io/engineerai'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
gem 'httparty'
gem 'google-cloud-vision', '~> 1.1', '>= 1.1.3'
gem 'whenever', require: false
gem 'ocr_space'
gem 'kimurai'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'dotenv-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_push_notifications-c0f9e9b7', '0.0.9', require: 'bx_block_push_notifications'
gem 'bx_block_admin', '0.0.11'
gem 'bx_block_catalogue-0e5da613', '0.0.6', require: 'bx_block_catalogue'
gem 'bx_block_data_import_export_csv-ec567cbb', '0.0.2', require: 'bx_block_data_import_export_csv'
gem 'account_block', '0.0.29'
gem 'bx_block_login-3d0582b5', '0.0.10', require: 'bx_block_login'
gem 'bx_block_upload_media-9de56634', '0.0.2', require: 'bx_block_upload_media'
gem 'bx_block_forgot_password-4de8968b', '0.0.6', require: 'bx_block_forgot_password'
gem 'bx_block_email_notifications', '0.0.3'
gem 'bx_block_visual_analytics', '0.1.1'
gem 'bx_block_advanced_search-23b25188', '0.0.2', require: 'bx_block_advanced_search'
gem 'bx_block_categories-acd0763f', '0.0.8', require: 'bx_block_categories'
gem 'bx_block_content_management', '0.0.2', require: 'bx_block_content_management'
gem 'bx_block_custom_form-63cd533b', '0.0.7', require: 'bx_block_custom_form'
gem 'bx_block_notifications-a22eb801', '0.0.3', require: 'bx_block_notifications'
gem 'builder_base', '0.0.43'
gem 'sassc-rails'
gem 'activeadmin'
gem 'active_admin_role'
gem 'activeadmin_json_editor'
gem 'active_admin_datetimepicker'
gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'
gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'
gem 'bx_block_cors'
gem 'twilio-ruby'
gem 'devise'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
gem 'active_admin_import'
gem 'activerecord-import'
gem 'pry'
gem 'rack-cors'